### ISSUE TITLE
Legg til ikon for kategorien Juss og data

### ISSUE THREAD

**Issue by shenluna** [datadeling/datafabrikken-portal#108]
Det kommer snart en ny kategori til Datalandsbyen, denne trenger ny ikon for visning i Datafabrikken.

https://drive.google.com/drive/folders/1M7BKueIpN576h5tVGZaM7AQ4DSxUncrV
community-data-law.svg

**Comment by jeffreiffers** [comment]
Vi kan ikke legge inn ikonen før den er lagt inn i datalandsbyen. Trenger ID for å koble til ikon.

**Comment by shenluna** [comment]
@jeffreiffers Trenger den å være i prod før vi kan legge til ikon? Kategorien er lagt til i staging hvis det hjelper.

**Comment by jeffreiffers** [comment]
Jeg endrer implementasjonen til å bruke navn isteden. ID genereres når kategorien opprettes, så kan ikke brukes.
