### ISSUE TITLE
[BRUKERHISTORIE] Fiks feil i e-post med samandrag

### ISSUE THREAD

**Issue by livarb** [datadeling/datafabrikken-portal#123]
Som: mottakar av samandrag på e-post
Ønsker jeg å: få ein e-post som ser pen ut
Slik at: eg fokuserer på innhaldet og ikkje blir forstyrra av utsjånaden

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

1. Det ser ut som eit parameter manglar ("fra% 1")
2. Plassholdar-profilbilde blir vist vrengt.

Slik ser eit samandrag ut i Outlook
![image](https://user-images.githubusercontent.com/3617256/143547049-7ebbde33-47c0-4c4c-9034-a7c82f63c119.png)

**Comment by livarb** [comment]
Pkt. 2 ser betre ut når ein mottar det i GMail:
![image](https://user-images.githubusercontent.com/3617256/143830320-f884d7b0-69ee-4279-9da3-809ec23d7ce7.png)

**Comment by jeffreiffers** [comment]
Pkt 2 tror ikke jeg kommer til å gjøre noe med siden det mest sannsynlig er render issue i outlook. Gjerne test eposten i en enda en epostklient.

**Comment by livarb** [comment]
@jeffreiffers : Då let vi pkt. 2 vere for no. Har ein sett noko på pkt. 1?

**Comment by jeffreiffers** [comment]
Vi har oppgradert til siste versjon (1.19). Du kan sjekke om feilen har blitt borte.

**Comment by livarb** [comment]
Supert. Skal sjekke det straks eg får ny e-post med samandrag. Ser ut som det er noko gale med e-postutsending (jamfør Slack-post).

**Comment by livarb** [comment]
Framleis feil på pkt. 1 i samandrag-e-posten eg fekk på søndag:
![image](https://user-images.githubusercontent.com/3617256/152978143-4150cbad-87a3-4718-839a-94f85646cf30.png)

**Comment by livarb** [comment]
Ser ut til at 1) er i orden no. Trudde vi måtte vente til ny versjon av NodeBB fekk med feilfiks? @jeffreiffers 
Om det ikkje er noko meir å legge til, så kan denne saka lukkast.

Her er samandrag-e-posten eg fekk i går:
![image](https://user-images.githubusercontent.com/3617256/153842750-be117f32-1010-4677-9163-73bdb185ccf6.png)

**Comment by jeffreiffers** [comment]
Jeg har manuelt overskrevet oversettelser midlertidig. Når vi kan bekrefte at dette er fikset i ny release skal jeg fjerne det. Lukker saken!
