### ISSUE TITLE
Heve metakvalitet for dcat:downloadURL

### ISSUE THREAD

**Issue by shenluna** [datadeling/datafabrikken-portal#139]
Se behov: https://github.com/datadeling/behov-issue-tracker/issues/120

I første omgang ønsker vi å få tatt ut en liste over datasett med lenker som er døde eller ikke gir data.
Listen skal inneholde informasjon om:
- Navn på datasett
- Navn på tilbyder 
- Distribusjon med dcat:downloadURL som ikke fungerer

**Comment by jeffreiffers** [comment]
[downloads.xlsx](https://github.com/datadeling/datafabrikken-portal/files/7674568/downloads.xlsx)
