### ISSUE TITLE
Endre navn på tilgangsnivå i datasett-søket og legge til ikke-allmenn tilgang

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/datafabrikken-portal#155]
1.  Endre navn på eksisterende kategorier
2.  Legge til `ikke-allmenn tilgang` som ny kategori

1: endre navn på eksisterende
|endre fra | endre til |
| ---- | -----| 
|åpne data | allmenn tilgang| 
| begrenset tilgang | betinget tilgang |

2: legge til kategori
Ettersom autocomplete gjør oppslag i hele datasettkatalogen, gir dette 404 når en velger et forslag som sortererer under det utelatte tilgangsnivået. Eksempel: søk på `tilsynsrapport`. I stedet for å fikse dette, ønsker jeg også at den siste kategorien inkluderes på datafabrikken. Her skal termen `ikke-allmenn tilgang` benyttes (heter pt. `unntatt offentlighet` på data.norge.no
 
Endringen kan gjennomføres som en ren navneendring nå - altså før https://github.com/Informasjonsforvaltning/behov/issues/634#issue-1045643541 er på plass.

**Comment by shenluna** [comment]
Vi ble enige om å endre begrenset tilgang til ikke åpne data. Dette er nå gjort, lukker dermed denne saken.
