### ISSUE TITLE
Legg til søkefelt på Datalandsbyen

### ISSUE THREAD

**Issue by shenluna** [datadeling/datafabrikken-portal#181]
Se behov: https://github.com/datadeling/behov-issue-tracker/issues/148
Se design: https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-d.html

I likhet med Datalandsbyen ønsker vi et søkefelt på Datalandsbyen inne på Datafabrikken.

Trenger design på søkeresultat

**Comment by LeneSundsbo** [comment]
Lenke til design: https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-search-d.html
