### ISSUE TITLE
Sitemap manglar frontend

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/datafabrikken-portal#206]
I footer er det lenka til [sitmap.xml](https://datafabrikken.norge.no/sitemap.xml). Her på vi få på plass ei html-side og endre lenke i footer.

**Comment by shenluna** [comment]
Vi tar inspirasjon fra Digdir sitt nettstedkart og gjør det samme, se eksempel: https://www.digdir.no/digdir/nettstedkart/858
