### ISSUE TITLE
Opprettelse av dynamisk veileder

### ISSUE THREAD

**Issue by shenluna** [datadeling/datafabrikken-portal#213]
Se behov: https://github.com/datadeling/behov-issue-tracker/issues/164

Eksempel på en dynamisk veileder:
https://dibk.no/verktoy-og-veivisere/bygg-uten-a-soke-garasje/

Deres github: 
https://github.com/DirektoratetForByggkvalitet/losen
https://github.com/DirektoratetForByggkvalitet/dibk-stort-bygge

**Comment by LeneSundsbo** [comment]
@jeffreiffers 

Mitt forslag til fargeendring:
[ - ] Grønn #00757F > blue-52
[ - ] Lys grå #F2F1F0 > blue-8
[ - ] Mørk #072938 > blue-52
[ - ] Lys gul #F0F2CB > blue-8
[ - ] Bakgrunnsgradering > solid blue-4 

Her er resultat:
![Screenshot 2022-05-30 at 13 18 24](https://user-images.githubusercontent.com/25385497/170981755-4eacbcdb-dc69-4bac-b0a0-c2141f3fd149.png)

**Comment by jeffreiffers** [comment]
Den kan vel lukkes?
