### ISSUE TITLE
Oppdater pil på forsiden til å bli klikkbar

### ISSUE THREAD

**Issue by shenluna** [datadeling/datafabrikken-portal#214]
På forsiden til datafabrikken er det en animert pil, denne er per dags dato ikke klikkbar. Vi ønsker at den skal bli klikkbar slik at man kommer til "neste side" av forsiden

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/13b2d2dd-0246-4e53-8355-5790ae65cf39)

**Comment by jeffreiffers** [comment]
https://github.com/datadeling/datafabrikken-portal-nextjs/pull/12
