### ISSUE TITLE
Lage løsningen - Datajegeren

### ISSUE THREAD

**Issue by shenluna** [datadeling/datafabrikken-portal#230]
Se behov: https://github.com/datadeling/behov-issue-tracker/issues/167
Se design: https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datahunter-d.html

- [x] Lage en nettside med skjemaløsning for å hente inn informasjon om hva slags datasett virksomheter trenger og hjelpe med å få tak i datasettet
- [ ] Legge til lenke til datajegeren til blindvei ved søk

[Lenke til word dokument](https://digdir.sharepoint.com/:w:/r/sites/Prosjekt_Datafabrikken/Delte%20dokumenter/3.%20Tjenesteutvikling/2.%20Datafabrikkens%20tjenestetilbud/Datajegeren/Datajegeren%20-%20beskrivelse%20av%20tjenesten%20og%20digital%20f%C3%B8rstelinje.docx?d=w705c79b5739a4d5da3abffb4059dd2be&csf=1&web=1&e=WFCHNB)

**Comment by shenluna** [comment]
Det er et ønske om å legge til lenke av datajegeren til blindvei ved søk av datasett

**Comment by jeffreiffers** [comment]
Blindvei skal implementeres i https://github.com/datadeling/behov-issue-tracker/issues/174
