### ISSUE TITLE
Opprette staging miljø for Datafabrikken

### ISSUE THREAD

**Issue by shenluna** [datadeling/datafabrikken-portal#26]
Ønsker opprettelse av et staging miljø for Datafabrikken for å teste ny funksjonalitet

**Comment by valosnah** [comment]
- [x] Opprette datafabrikken-dev prosjekt
- [x] Opprette service accounts
- [x] Fikse networking
- [x] Opprette datafabrikken-dev Kubernetes cluster
- [x] Sette opp sikkerhet (TLS/cloud armor)
- [ ] Bestille sertifikat(er)
- [ ] Lande og bestille DNS records
- [ ] Legge inn sertifikat(er)
- [ ] Oppdatere helm-templates
- [ ] Legge til staging-workflows
- [ ] Legge inn Github-secrets
- [ ] Legge inn GCP-secrets
