### ISSUE TITLE
Endre tilgangsnivå-filteret fra AND til OR 

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/datafabrikken-portal#94]
De to verdiene som ligger i filteret "åpne data" og "begrenset tilgang" er gjensidig utelukkende verdier som ikke kan kombineres. Et datasett kan altså ikke være begge deler. Jeg kan nå krysse av for begge, noe som alltid vil gi null treff. Eksempel: https://datafabrikken.norge.no/finn-data/sok-datasett?q=enhet&opendata=true&accessRights=true

Løsningsforslag: 
1. Endre fra AND til OR: Når jeg velger begge kategoriene må trefflisten vise summen av begge - ikke de datasettene som er i begge kategorier (det vil alltid være null).
2. Endre fra checkboks til radioknapper slik at kun et av valgene kan velges om gangen.

**Comment by shenluna** [comment]
Vi løser dette ved bruk at løsningsforslag 2.
